# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Provides an essential, core set of commands for Bukkit.
softdepend: [Vault, LuckPerms]
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685]
api-version: "1.13"
commands:
  anvil:
    description: Opens up an Anvil.
    usage: /<command>
    aliases: [eanvil]
  back:
    description: Teleports you to your location prior to tp/spawn/warp.
    usage: /<command> [player]
    aliases: [eback,return,ereturn]
  balancetop:
    description: Gets the top balance values.
    usage: /<command> <page>
    aliases: [ebalancetop,baltop,ebaltop]
  book:
    description: Allows reopening and editing of sealed books.
    usage: /<command> [title|author [name]]
    aliases: [ebook]
  createkit:
    description: Create a kit in game!
    usage: /<command> <kit> <delay>
    aliases: [kitcreate,createk,kc,ck]
  delkit:
    description: Deletes the specified kit.
    usage: /<command> <kit>
    aliases: [edelkit,remkit,eremkit,rmkit,ermkit,deletekit,edeletekit]
  disposal:
    description: Opens a portable disposal menu.
    usage: /<command>
    aliases: [edisposal,trash,etrash]
  eco:
    description: Manages the server economy.
    usage: /<command> <give|take|set|reset> <player> <amount>
    aliases: [eeco,economy,eeconomy]
  enchant:
    description: Enchants the item the user is holding.
    usage: /<command> <enchantmentname> [level]
    aliases: [eenchant,enchantment,eenchantment]
  essentials:
    description: Reloads essentials.
    usage: /<command>
    aliases: [eessentials, ess, eess, essversion]
  exp:
    description: Give, set, reset, or look at a players experience.
    usage: /<command> [reset|show|set|give] [player [amount]]
    aliases: [eexp,xp]
  ext:
    description: Extinguish players.
    usage: /<command> [player]
    aliases: [eext,extinguish,eextinguish]
  give:
    description: Give a player an item.
    usage: /<command> <player> <item|numeric> [amount [itemmeta...]]
    aliases: [egive]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
    aliases: [einvsee]
  item:
    description: Spawn an item.
    usage: /<command> <item|numeric> [amount [itemmeta...]]
    aliases: [i,eitem,ei]
  itemdb:
    description: Searches for an item.
    usage: /<command> <item>
    aliases: [dura,edura,durability,edurability,eitemdb,itemno,eitemno]
  itemlore:
    description: Edit the lore of an item.
    usage: /<command> <add/set/clear> [text/line] [text]
    aliases: [lore, elore, ilore, eilore, eitemlore]
  itemname:
    description: Names an item.
    usage: /<command> [name]
    aliases: [iname, einame, eitemname, itemrename, irename, eitemrename, eirename]
  kit:
    description: Obtains the specified kit or views all available kits.
    usage: /<command> [kit] [player]
    aliases: [ekit,kits,ekits]
  near:
    description: Lists the players near by or around a player.
    usage: /<command> [player] [radius]
    aliases: [enear,nearby,enearby]
  pay:
    description: Pays another player from your balance.
    usage: /<command> <player> <amount>
    aliases: [epay]
  paytoggle:
    description: Toggles whether you are accepting payments.
    usage: /<command>
    aliases: [epaytoggle, payoff, epayoff, payon, epayon]
  payconfirmtoggle:
    description: Toggles whether you are prompted to confirm payments.
    usage: /<command>
    aliases: [epayconfirmtoggle, payconfirmoff, epayconfirmoff, payconfirmon, epayconfirmon, payconfirm, epayconfirm]
  potion:
    description: Adds custom potion effects to a potion.
    usage: /<command> <clear|apply|effect:<effect> power:<power> duration:<duration>>
    aliases: [epotion,elixer,eelixer]
  powertool:
    description: Assigns a command to the item in hand.
    usage: /<command> [l:|a:|r:|c:|d:][command] [arguments] - {player} can be replaced by name of a clicked player.
    aliases: [epowertool,pt,ept]
  powertooltoggle:
    description: Enables or disables all current powertools.
    usage: /<command>
    aliases: [epowertooltoggle,ptt,eptt,pttoggle,epttoggle]
  repair:
    description: Repairs the durability of one or all items.
    usage: /<command> [hand|all]
    aliases: [fix,efix,erepair]
  seen:
    description: Shows the last logout time of a player.
    usage: /<command> <player>
    aliases: [eseen]
  showkit:
    description: Show contents of a kit.
    usage: /<command> <kit>
    aliases: [kitpreview,preview,kitshow]
  editsign:
    description: Edits a sign in the world.
    usage: /<command> <set/clear> <line number> [text]
    aliases: [sign, esign, eeditsign]
  skull:
    description: Set the owner of a player skull
    usage: /<command> [owner]
    aliases: [eskull, playerskull, eplayerskull, head, ehead]
  sudo:
    description: Make another user perform a command.
    usage: /<command> <player> <command [args]>
    aliases: [esudo]
  workbench:
    description: Opens up a workbench.
    usage: /<command>
    aliases: [craft,ecraft,wb,ewb,wbench,ewbench,eworkbench]

permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
    children:
      essentials.gamemode.*: true
  # These permissions can't be assigned from player-commands for compatibility reasons
  essentials.teleport.cooldown.bypass.tpa:
    default: true
    description: If the player does not have this permission, /tpa will have cooldown even with the parent bypass perm
  essentials.teleport.cooldown.bypass.back:
    default: true
    description: If the player does not have this permission, /back will have cooldown even with the parent bypass perm
  essentials.gamemode.*:
    default: op
    children:
      essentials.gamemode: true
      essentials.gamemode.others: true
      essentials.gamemode.all: true
  essentials.seen.extra:
    default: op
    children:
      essentials.seen.ip: true
      essentials.seen.location: true
  essentials.keepinv:
    default: false
    description: Controls whether players keep their inventory on death.
  essentials.near.exclude:
    default: false
    description: If the player should be excluded from near lookups.
  essentials.keepxp:
    default: false
    description: Allows the user to keep their exp on death, instead of dropping it.
  essentials.invsee.preventmodify:
    default: false
    description: Prevents other players from modifying the players inventory.
  essentials.afk.auto:
    default: false
    description: Players with this permission will be set to afk after a period of inaction as defined in the config file.
  essentials.home.compass:
    default: false
    description: Point the player's compass at their first home. compass-towards-home-perm needs to be enabled in the configuration.
  essentials.ban.exempt:
    default: false
    description: Prevent a specified group or player from being banned
  essentials.kick.exempt:
    default: false
    description: Prevents the player from being kicked.
  essentials.chat.ignoreexempt:
    default: false
    description: Someone with this permission will not be ignored, even if they are on another persons ignore list
  essentials.kit.exemptdelay:
    default: false
    description: Exempts you from the kit delay feature, this affects signs as well as command.
  essentials.mute.exempt:
    default: false
    description: Prevent a specified group or player from being muted
  essentials.sethome.bed:
    default: false
    description: Allows the player to right click a bed during daytime to update their 'bed' home.
  essentials.silentjoin:
    default: false
    description: Allow to join silently
  essentials.silentjoin.vanish:
    default: false
    description: Allow to join silently, and get put in vanish mode
  essentials.silentquit:
    default: false
    description: Suppress leave/quit messages for users with this permission.
  essentials.sudo.exempt:
    default: false
    description: Prevents the holder from being sudo'ed by another user
  essentials.tempban.exempt:
    default: false
    description: Prevents a specified group or player from being tempbanned
  essentials.nick.allowunsafe:
    default: false
    description: If a player has this, they can set their username to any value. Use with caution, as this has the potential to break userdata files.
  essentials.balancetop.exclude:
    default: false
    description: Players with this permission are excluded from the balancetop
  essentials.back.onteleport:
    default: true
    description: Players with this permission will have back location stored during any teleportation
  essentials.back.ondeath:
    default: false
    description: Players with this permission will have back location stored during death
  essentials.exempt:
    default: false
    description: Parent permission to be exempt from many moderator actions
    children:
      essentials.invsee.preventmodify: true
      essentials.ban.exempt: true
      essentials.kick.exempt: true
      essentials.mute.exempt: true
      essentials.chat.ignoreexempt: true
      essentials.sudo.exempt: true
      essentials.tempban.exempt: true
      essentials.exempt.protect: true
